# Generated by Django 5.1 on 2024-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chat_messages_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.FileField(default=False, null=True, upload_to='photos/users/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/users/user0.png', null=True, upload_to='photos/users/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
