# Generated by Django 5.1 on 2024-11-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messages_file_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(null=True),
        ),
    ]
