# Generated by Django 5.1 on 2024-11-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comments_options_comments_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['time_created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
